### ISSUE TITLE
1.2.4 is on NPM but not on git repo

### ISSUE THREAD

**Issue by cmdcolin** [rbuels/http-range-fetcher#24]
https://www.npmjs.com/package/http-range-fetcher is at 1.2.4

https://github.com/rbuels/http-range-fetcher/tags has no 1.2.4

I saw this because looking at dependencies I see that conventional-changelog-angular is included as a "runtime dependency" somewhere down the line still which https://github.com/rbuels/http-range-fetcher/commit/b227857cc682fc2b980d1820f8a413bba6e37470 was meant to fix

**Comment by cmdcolin** [comment]
Probably we just want to release 1.2.5 since b227857 was added after 1.2.4 was released

**Comment by rbuels** [comment]
oops forgot to push it, fixed

**Comment by rbuels** [comment]
ok, released 1.2.5

**Comment by cmdcolin** [comment]
just for reference, in other packages, I modified "postpublish" to "postversion" in the scripts in package.json for automatically pushing it
